#!/bin/bash

# Navigate to the linkblog directory
# cd /home/ftricas/usr/src/Python/deGitHub/linkblog

# Get yesterday's date in YYYY-MM-DD format
yesterday=$(date -d "yesterday" +%Y-%m-%d)

# Generate the post for yesterday
python3 scripts/list_twitter_links_by_date.py "$yesterday"

# Add, commit, and push the new post
# The filename generated by the python script is "YYYY-MM-DD-twitter-links.md"
git add _posts/"$yesterday"-twitter-links.md
git commit -m "Add post for $yesterday"
git push
