#!/bin/bash

# Navigate to the linkblog directory
cd "$HOME/usr/src/web/deGitHub/linkblog"

# Check if a date parameter is provided
if [ -n "$1" ]; then
  # Use the provided date if available
  target_date="$1"
else
  # Get yesterday's date in YYYY-MM-DD format if no date is provided
  target_date=$(date -d "yesterday" +%Y-%m-%d)
fi

# Generate the post for the target date
~/.pyenv/shims/python scripts/list_links_by_date.py "$target_date"

# Add, commit, and push the new post
# The filename generated by the python script is "YYYY-MM-DD-links.md"
git add _posts/"$target_date"-links.md
git commit -m "Add post for $target_date"
git push
